name : CI

on: 
  push:
    branches: 
      - main

jobs: 
  deploy:
    runs-on: ubuntu-latest
  
    steps: 
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js 
      uses: actions/setup-node@v3
      with: 
        node-version: "24"

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
    
    - name : Trigger Render Deployement
      env : 
        RENDER_DEPLOY_HOOK_URL: ${{ secret.RENDER_DEPLOY_HOOK_URL }}
      run : |
        curl -X POST "$RENDER_DEPLOY_HOOK_URL"
